name: Build Dockerfile and Push Github Package Registry
on:
  push:
    branches:
      - develop

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        cd docker/ && make build && cd ../
    - name: Push to Github Package Registry
      run: |
        docker login docker.pkg.github.com -u nobiki -p ${{ secrets.GH_ACCESS_TOKEN }}
        docker tag actions-example docker.pkg.github.com/nobiki/actions-test/actions-example:latest
        docker push docker.pkg.github.com/nobiki/actions-test/actions-example:latest


jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@develop

    - name: Build Image
      run: |
        echo ${GITHUB_SHA::8}
        cd docker/ && docker build -f Dockerfile_original.dockerfile -t docker.pkg.github.com/yamap55/original:${GITHUB_SHA::8} .
