name: Build Dockerfile and Push Github Package Registry
on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        echo ${GITHUB_SHA::8}
        cd docker/ && docker build -f Dockerfile_original.dockerfile -t docker.pkg.github.com/yamap55/original:${GITHUB_SHA::8} .
